import { IMAGES } from "./images";

export const STORES = [
  {
    title: 'World Foods',
    description: 'We\'re here for you, Portland.',
    time: 'Today, 11 AM',
    lat: -33.939702,
    lng: 151.194888,
    image: '/assets/stores/1.png',
    marker: IMAGES.IconPin1Map
  },
  {
    title: 'Walmart',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.940033,
    lng: 151.193451,
    image: '/assets/stores/2.png',
    marker: IMAGES.IconPin2Map
  },
  {
    title: 'Longos',
    description: 'A fresh tradition',
    time: 'Today, 2 PM',
    lat: -33.941826,
    lng: 151.195311,
    image: '/assets/stores/3.png',
    marker: IMAGES.IconPin2Map
  },
  {
    title: 'Target',
    description: 'Expect More. Pay Less.',
    time: 'Today, 11AM - 6 PM',
    lat: -33.940247,
    lng: 151.196579,
    image: '/assets/stores/4.png',
    marker: IMAGES.IconPin4Map
  },
  {
    title: 'World Foods',
    description: 'We\'re here for you, Portland.',
    time: 'Today, 11 AM',
    lat: -33.940585,
    lng: 151.196297,
    image: '/assets/stores/5.png',
    marker: IMAGES.IconPin4Map
  },
  {
    title: 'World Foods',
    description: 'We\'re here for you, Portland.',
    time: 'Today, 11 AM',
    lat: -33.941085,
    lng: 151.196297,
    image: '/assets/stores/5.png',
    marker: IMAGES.IconPinBreadMap
  },
  {
    title: 'World Foods',
    description: 'We\'re here for you, Portland.',
    time: 'Today, 11 AM',
    lat: -33.941125,
    lng: 151.196597,
    image: '/assets/stores/5.png',
    marker: IMAGES.IconPinBreadMap
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.940683,
    lng: 151.197217,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Longos',
    description: 'A fresh tradition',
    time: 'Today, 2 PM',
    lat: -33.940782,
    lng: 151.194227,
    image: '/assets/stores/7.png',
    marker: IMAGES.IconPinWineMap
  },
  {
    title: 'Longos',
    description: 'A fresh tradition',
    time: 'Today, 2 PM',
    lat: -33.941382,
    lng: 151.194227,
    image: '/assets/stores/7.png',
    marker: IMAGES.IconPinWineMap
  },
  {
    title: 'Target',
    description: 'Expect More. Pay Less.',
    time: 'Today, 11AM - 6 PM',
    lat: -33.941881,
    lng: 151.194207,
    image: '/assets/stores/8.png',
    marker: IMAGES.IconPin3Map
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.941683,
    lng: 151.197217,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.942083,
    lng: 151.196217,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.939583,
    lng: 151.196217,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.939983,
    lng: 151.196017,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.941043,
    lng: 151.195817,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.941043,
    lng: 151.195817,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Target',
    description: 'Expect More. Pay Less.',
    time: 'Today, 11AM - 6 PM',
    lat: -33.940881,
    lng: 151.195007,
    image: '/assets/stores/8.png',
    marker: IMAGES.IconPin3Map
  },
  {
    title: 'Target',
    description: 'Expect More. Pay Less.',
    time: 'Today, 11AM - 6 PM',
    lat: -33.940581,
    lng: 151.195407,
    image: '/assets/stores/8.png',
    marker: IMAGES.IconPin3Map
  },
  {
    title: 'Target',
    description: 'Expect More. Pay Less.',
    time: 'Today, 11AM - 6 PM',
    lat: -33.941581,
    lng: 151.195307,
    image: '/assets/stores/8.png',
    marker: IMAGES.IconPin3Map
  },
  {
    title: 'Target',
    description: 'Expect More. Pay Less.',
    time: 'Today, 11AM - 6 PM',
    lat: -33.941381,
    lng: 151.195207,
    image: '/assets/stores/8.png',
    marker: IMAGES.IconPin3Map
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.940983,
    lng: 151.196017,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.941983,
    lng: 151.195017,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.940099,
    lng: 151.195017,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.94,
    lng: 151.195,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.941,
    lng: 151.194,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.941,
    lng: 151.1945,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.9413,
    lng: 151.1946,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.9416,
    lng: 151.1946,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.9413,
    lng: 151.1946,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Grocery',
    description: 'Save money. Live better',
    time: 'Today, 11 AM',
    lat: -33.9416,
    lng: 151.1943,
    image: '/assets/stores/6.png',
    marker: IMAGES.IconPinCatMap
  },
  {
    title: 'Longos',
    description: 'A fresh tradition',
    time: 'Today, 2 PM',
    lat: -33.940,
    lng: 151.194,
    image: '/assets/stores/7.png',
    marker: IMAGES.IconPinWineMap
  },
  {
    title: 'Longos',
    description: 'A fresh tradition',
    time: 'Today, 2 PM',
    lat: -33.9404,
    lng: 151.1943,
    image: '/assets/stores/7.png',
    marker: IMAGES.IconPinWineMap
  },
  {
    title: 'Longos',
    description: 'A fresh tradition',
    time: 'Today, 2 PM',
    lat: -33.9405,
    lng: 151.1946,
    image: '/assets/stores/7.png',
    marker: IMAGES.IconPinWineMap
  },
  {
    title: 'Longos',
    description: 'A fresh tradition',
    time: 'Today, 2 PM',
    lat: -33.9409,
    lng: 151.1943,
    image: '/assets/stores/7.png',
    marker: IMAGES.IconPinWineMap
  },
  {
    title: 'Longos',
    description: 'A fresh tradition',
    time: 'Today, 2 PM',
    lat: -33.9405,
    lng: 151.196,
    image: '/assets/stores/7.png',
    marker: IMAGES.IconPinWineMap
  },
  {
    title: 'Longos',
    description: 'A fresh tradition',
    time: 'Today, 2 PM',
    lat: -33.9404,
    lng: 151.1956,
    image: '/assets/stores/7.png',
    marker: IMAGES.IconPinWineMap
  },
  {
    title: 'Longos',
    description: 'A fresh tradition',
    time: 'Today, 2 PM',
    lat: -33.940826,
    lng: 151.195211,
    image: '/assets/stores/3.png',
    marker: IMAGES.IconMapPointMap
  },
]

export const FILTERS = [
  {
    title: 'Apparel',
    products: 1196,
    image: './assets/filters/apparel.svg'
  },
  {
    title: 'Automotive',
    products: 1196,
    image: './assets/filters/automotive.svg'
  },
  {
    title: 'Baby Products',
    products: 645,
    image: './assets/filters/baby-products.svg'
  },
  {
    title: 'Beauty Products',
    products: 215,
    image: './assets/filters/beauty-products.svg'
  },
  {
    title: 'Food & Grocery',
    products: 2881,
    image: './assets/filters/food-grocery.svg'
  },
  {
    title: 'Beverages',
    products: 452,
    image: './assets/filters/beverages.svg'
  },
  {
    title: 'Gaming',
    products: 452,
    image: './assets/filters/gaming.svg'
  },
  {
    title: 'Health & Care',
    products: 269,
    image: './assets/filters/health-care.svg'
  },
  {
    title: 'Industrial',
    products: 519,
    image: './assets/filters/industrial.svg'
  },
  {
    title: 'Handmade',
    products: 519,
    image: './assets/filters/handmade.svg'
  },
  {
    title: 'Toys',
    products: 519,
    image: './assets/filters/toys.svg'
  },
  {
    title: 'Bags & Luggage',
    products: 519,
    image: './assets/filters/bags-luggage.svg'
  },
  {
    title: 'Audio',
    products: 519,
    image: './assets/filters/audio.svg'
  },
]

export const GOOGLE_API_KEY = 'AIzaSyAvi8izJBiY5SXocu2gM-UH0cVr6LDpGks'

export const DEMANDPRODUCTS = [
  {
    img: IMAGES.ImgOliveProduct,
    prev_price: 4.79,
    new_price: 4.79,
    title: 'Gallo Extra Virgin Olive Oil',
    description: '16 OZ',
    color: 'rgb(240, 250, 243)',
    company: 'World Foods',
    percent: -38
  },
  {
    img: IMAGES.ImgCiderProduct,
    prev_price: 2.79,
    new_price: 4.79,
    title: 'Natural Vinegar Apple Cider',
    description: '16 OZ',
    color: 'rgb(240, 250, 243)',
    company: 'Walmart',
    percent: -38
  },
  {
    img: IMAGES.ImgFaceMaskProduct,
    prev_price: 2.79,
    new_price: 4.79,
    title: 'Surgical Face Mask - 5 Pack',
    description: '16 OZ',
    color: 'rgb(228, 249, 255)',
    company: 'World Foods',
    percent: -20
  },

  {
    img: IMAGES.ImgGreenOnionProduct,
    prev_price: 2.79,
    new_price: 4.79,
    title: 'Green Onion',
    description: 'Price/UnitZ',
    color: 'rgb(228, 249, 255)',
    company: 'Metro',
    percent: -16
  },
  {
    img: IMAGES.ImgOliveProduct,
    prev_price: 4.79,
    new_price: 4.79,
    title: 'Gallo Extra Virgin Olive Oil',
    description: '16 OZ',
    color: 'rgb(240, 250, 243)',
    company: 'World Foods',
    percent: -15
  },
  {
    img: IMAGES.ImgCiderProduct,
    prev_price: 2.79,
    new_price: 4.79,
    title: 'Gallo Extra Virgin Olive Oil',
    description: '16 OZ',
    color: 'rgb(228, 249, 255)',
    company: 'World Foods',
    percent: -14
  },
  {
    img: IMAGES.ImgFaceMaskProduct,
    prev_price: 2.79,
    new_price: 4.79,
    title: 'Gallo Extra Virgin Olive Oil',
    description: '16 OZ',
    color: 'rgb(240, 250, 243)',
    company: 'Metro',
    percent: -13
  },
  {
    img: IMAGES.ImgYellowOnionProduct,
    prev_price: 2.79,
    new_price: 4.79,
    title: 'Gallo Extra Virgin Olive Oil',
    description: '16 OZ',
    color: 'rgb(228, 249, 255)',
    company: 'World Foods',
    percent: -10
  },
  {
    img: IMAGES.ImgGreenOnionProduct,
    prev_price: 2.79,
    new_price: 4.79,
    title: 'Gallo Extra Virgin Olive Oil',
    description: '16 OZ',
    color: 'rgb(228, 249, 255)',
    company: 'Metro',
    percent: -10
  },
]

export const FOODSPRODUCTS = [
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  }
]

export const STORESPRODUCTS = [
  {
    img: IMAGES.ImgFoodStore,
    cimg: IMAGES.Img1LogoStore,
    title: '01 - Groceries',
    description: 'World Foods',
  },
  {
    img: IMAGES.ImgMetroStore,
    cimg: IMAGES.Img2LogoStore,
    title: '02 - Groceries',
    description: 'Metro',
  },
  {
    img: IMAGES.ImgWalmartStore,
    cimg: IMAGES.Img3LogoStore,
    title: '03 - Groceries',
    description: 'Walmart',
  },
  {
    img: IMAGES.ImgMetroStore,
    cimg: IMAGES.Img4LogoStore,
    title: '04 - Groceries',
    description: 'Metro',
  },
  {
    img: IMAGES.ImgFoodStore,
    cimg: IMAGES.Img5LogoStore,
    title: '05 - Groceries',
    description: 'Food',
  }
]

export const FOODSPRODUCTS2 = [
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPhoto,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgTomatoVegetableProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgPotatoVegetableProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgBananaVegetableProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCauliflowerVegetableProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
]

export const CATEGORIES = [
  {
    title: 'Alcoholic Beverages',
    products: 1196,
    image: IMAGES.IconAlcoholicCategory,
    cId: 'category01',
    sub: [
      {sId: '01-01', title: 'Beer'},
      {sId: '01-02', title: 'Bitters'},
      {sId: '01-03', title: 'Cider'},
      {sId: '01-04', title: 'Liquor'},
      {sId: '01-05', title: 'Liqueurs'},
      {sId: '01-06', title: 'Sparkling'},
      {sId: '01-07', title: 'Wine'},
      {sId: '01-08', title: 'Other'},
    ]
  },
  {
    title: 'Clothing, Footwear & Jewelry',
    products: 1196,
    image: IMAGES.IconClothingCategory,
    cId: 'category02',
    sub: [
      {sId: '02-01', title: "Men's Clothing"},
      {sId: '02-02', title: "Women's Clothing"},
      {sId: '02-03', title: "Maternity Clothing"},
      {sId: '02-04', title: "Baby Boy's Clothing"},
      {sId: '02-05', title: "Baby Girl's Clothing"},
      {sId: '02-06', title: "Teen Boys & Kids Clothing"},
      {sId: '02-07', title: "Teen Girls & Kids Clothing"},
      {sId: '02-08', title: "Men's Footwear"},
      {sId: '02-09', title: "Women's Footwear"},
      {sId: '02-10', title: "Baby Footwear"},
      {sId: '02-11', title: "Teen & Kids Boys footwear"},
      {sId: '02-12', title: "Teen & Kids Girls footwear"},
      {sId: '02-13', title: "Footwear Accessories"},
      {sId: '02-14', title: "Jewelry & Watches"},
      {sId: '02-15', title: "Swimwear"},
      {sId: '02-16', title: "Eye Wear"},
      {sId: '02-17', title: "Accessories"},
      {sId: '02-18', title: "Other"},
    ]
  },
  {
    title: 'Arts, Crafts & Office Supplies',
    products: 645,
    image: IMAGES.IconArtsCategory,
    cId: 'category03',
    sub: [
      {sId: '03-01', title: "Office Supplies"},
      {sId: '03-02', title: "Children's Art & Crafts"},
      {sId: '03-03', title: "Art & Crafts"},
      {sId: '03-04', title: "Baking Supplies"},
      {sId: '03-05', title: "Fabric"},
      {sId: '03-06', title: "Crafts & Hobbies"},
      {sId: '03-07', title: "Frame"},
      {sId: '03-08', title: "Floral"},
      {sId: '03-09', title: "Home Office"},
      {sId: '03-10', title: "Painting & Painting Supplies"},
      {sId: '03-11', title: "Paper & Cards"},
      {sId: '03-12', title: "Partyy Supplies"},
      {sId: '03-13', title: "Printmaking & Scrapbooking"},
      {sId: '03-14', title: "Seasonal"},
      {sId: '03-15', title: "Beads & Jewelry"},
      {sId: '03-16', title: "Yarn & Needle Crafts"},
      {sId: '03-17', title: "Handmade"},
      {sId: '03-18', title: "Other"},
    ]
  },
  {
    title: 'Beauty, Body & Health',
    products: 215,
    image: IMAGES.IconBeautyCategory,
    cId: 'category04',
    sub: [
      {sId: '04-01', title: "Bath & Body"},
      {sId: '04-02', title: "Hair Care"},
      {sId: '04-03', title: "Make-up"},
      {sId: '04-04', title: "Nail Care"},
      {sId: '04-05', title: "Skin Care"},
      {sId: '04-06', title: "Tools & Accessories"},
      {sId: '04-07', title: "Dental Care"},
      {sId: '04-08', title: "Fragrances"},
      {sId: '04-09', title: "Candles & Scents"},
      {sId: '04-10', title: "Shaving"},
      {sId: '04-11', title: "Wellness"},
      {sId: '04-12', title: "Nutrition"},
      {sId: '04-13', title: "Sex & Sensuality"},
      {sId: '04-14', title: "Eye care"},
      {sId: '04-15', title: "Other"},
    ]
  },
  {
    title: 'Electronics, Music & Video',
    products: 2881,
    image: IMAGES.IconElectronicsCategory,
    cId: 'category05',
    sub: [
      {sId: '05-01', title: "Computers & Tablets"},
      {sId: '05-02', title: "Cameras & Camcorders"},
      {sId: '05-03', title: "Phones"},
      {sId: '05-04', title: "Audio"},
      {sId: '05-05', title: "Video Games"},
      {sId: '05-06', title: "Movies & Music"},
      {sId: '05-07', title: "Smart Home, Secuirty & Wi-Fi"},
      {sId: '05-08', title: "Home Cinema, TV & Video"},
      {sId: '05-09', title: "Musical Instruments"},
      {sId: '05-10', title: "Wearable Tech"},
      {sId: '05-11', title: "Vehicle Electronics & GPS"},
      {sId: '05-12', title: "Office Electronics"},
      {sId: '05-13', title: "Musical Instruments"},
      {sId: '05-14', title: "Other Electronics"},
      {sId: '05-15', title: "Electronic Accessories"},
      {sId: '05-16', title: "Other"},
    ]
  },
  {
    title: 'Sports, Outdoor & Fitness',
    products: 452,
    image: IMAGES.IconSportsCategory,
    cId: 'category06',
    sub: [
      {sId: '06-01', title: "Camping & Hiking"},
      {sId: '06-02', title: "Water & Swimming"},
      {sId: '06-03', title: "Fishing & Hiking"},
      {sId: '06-04', title: "Baseball & Softball"},
      {sId: '06-05', title: "Soccer"},
      {sId: '06-06', title: "Basketball"},
      {sId: '06-07', title: "Football"},
      {sId: '06-08', title: "Raquet Sports"},
      {sId: '06-09', title: "Golf"},
      {sId: '06-10', title: "Indoor Sports & Games"},
      {sId: '06-11', title: "Outdoor Sports & Games"},
      {sId: '06-12', title: "Fitness & Training"},
      {sId: '06-13', title: "Gym Equipment"},
      {sId: '06-14', title: "Apparel"},
      {sId: '06-15', title: "Fan Shop"},
      {sId: '06-16', title: "Bikes and Boards"},
      {sId: '06-17', title: "Specialty"},
      {sId: '06-18', title: "Accessories"},
      {sId: '06-19', title: "Other"},
    ]
  },
  {
    title: 'Home & Garden',
    products: 452,
    image: IMAGES.IconHomeCategory,
    cId: 'category07',
    sub: [
      {sId: '07-01', title: "Home"},
      {sId: '07-02', title: "Kitchen & Dining"},
      {sId: '07-03', title: "Bathroom"},
      {sId: '07-04', title: "Bedding & Linens"},
      {sId: '07-05', title: "Baby Home"},
      {sId: '07-06', title: "Storage & Organization"},
      {sId: '07-07', title: "Wedding"},
      {sId: '07-08', title: "Indoor furniture"},
      {sId: '07-09', title: "Candles & Decor"},
      {sId: '07-10', title: "Home Improvement"},
      {sId: '07-11', title: "Lighting and Fans"},
      {sId: '07-12', title: "Appliances"},
      {sId: '07-13', title: "Garden & Yard"},
      {sId: '07-14', title: "Outdoor & Patio Furniture"},
      {sId: '07-15', title: "Buildin Supplies"},
      {sId: '07-16', title: "Flower & platns"},
      {sId: '07-17', title: "Tools & Equipment"},
      {sId: '07-18', title: "Other"},
    ]
  },
  {
    title: 'Food, Grocery & Beverages',
    products: 269,
    image: IMAGES.IconFoodCategory,
    cId: 'category08',
    sub: [
      {sId: '08-01', title: "Farm Fresh Food"},
      {sId: '08-02', title: "Bakery & Desserts"},
      {sId: '08-03', title: "Fast Food"},
      {sId: '08-04', title: "Groceries"},
      {sId: '08-05', title: "International"},
      {sId: '08-06', title: "Speciality & Diet products"},
      {sId: '08-07', title: "Produce"},
      {sId: '08-08', title: "Pantry Items"},
      {sId: '08-09', title: "Dairy"},
      {sId: '08-10', title: "Fruits & Vegetables"},
      {sId: '08-11', title: "Meat, Poultry & Seafood"},
      {sId: '08-12', title: "Beverages (Non-Alcoholic)"},
      {sId: '08-13', title: "Other"},
    ]
  },
  {
    title: 'Toys & Gaming',
    products: 519,
    image: IMAGES.IconToysCategory,
    cId: 'category09',
    sub: [
      {sId: '09-01', title: "Action Figures"},
      {sId: '09-02', title: "Building & ConstructionToys"},
      {sId: '09-03', title: "Dolls & Playsets"},
      {sId: '09-04', title: "Educational Toys"},
      {sId: '09-05', title: "Electronic Toys"},
      {sId: '09-06', title: "Baby & Toddler Toys"},
      {sId: '09-07', title: "Kitchen & Food Toys"},
      {sId: '09-08', title: "Sports Toys & Outdoor"},
      {sId: '09-09', title: "Board Games & Puzzles"},
      {sId: '09-10', title: "Stuffed Animals"},
      {sId: '09-11', title: "Die-Cast & Toy Vehicles"},
      {sId: '09-12', title: "Musical Toy Instruments"},
      {sId: '09-13', title: "Video Games"},
      {sId: '09-14', title: "Hobbies"},
      {sId: '09-15', title: "Other"},
    ]
  },
  {
    title: 'Automotive & Industrial',
    products: 519,
    image: IMAGES.IconAutomotiveCategory,
    cId: 'category10',
    sub: [
      {sId: '10-01', title: "Auto Parts"},
      {sId: '10-02', title: "Interior Accessories"},
      {sId: '10-03', title: "Exterior Accessories"},
      {sId: '10-04', title: "Truck and RV"},
      {sId: '10-05', title: "Motorbike Accessories & Parts"},
      {sId: '10-06', title: "Batteries & Accessories"},
      {sId: '10-07', title: "Tools"},
      {sId: '10-08', title: "Performance"},
      {sId: '10-09', title: "Fluids and Adhesives"},
      {sId: '10-10', title: "Safety & Security"},
      {sId: '10-11', title: "Pipes, Hoses, Tubes & Fittings"},
      {sId: '10-12', title: "Fasteners and Hardware"},
      {sId: '10-13', title: "Metalworking & Fabrication"},
      {sId: '10-14', title: "Cleaning & Janitorial"},
      {sId: '10-15', title: "Electrical"},
      {sId: '10-16', title: "Plumbing"},
      {sId: '10-17', title: "Other"},
    ]
  },
  {
    title: 'Bags & Luggage',
    products: 519,
    image: IMAGES.IconBagsCategory,
    cId: 'category11',
    sub: [
      {sId: '11-01', title: "Hand Bags and Purses"},
      {sId: '11-02', title: "Travel Bags"},
      {sId: '11-03', title: "Back Packs"},
      {sId: '11-04', title: "Eheeled Bags"},
      {sId: '11-05', title: "Garment Bags"},
      {sId: '11-06', title: "Hard Luggage"},
      {sId: '11-07', title: "Soft Luggage"},
      {sId: '11-08', title: "Wallets"},
      {sId: '11-09', title: "Travel Accessories"},
      {sId: '11-10', title: "Technology Travel Bags"},
      {sId: '11-11', title: "Baby Travel Accessories"},
      {sId: '11-12', title: "Other"},
    ]
  },
  {
    title: 'Pet Supplies',
    products: 519,
    image: IMAGES.IconPetCategory,
    cId: 'category12',
    sub: [
      {sId: '12-01', title: "Birds"},
      {sId: '12-02', title: "Cats"},
      {sId: '12-03', title: "Dogs"},
      {sId: '12-04', title: "Fish & Aquatic Pets"},
      {sId: '12-05', title: "Horses"},
      {sId: '12-06', title: "Insects"},
      {sId: '12-07', title: "Reptiles & Amphibians"},
      {sId: '12-08', title: "Other"},
    ]
  },
  {
    title: 'Books',
    products: 519,
    image: IMAGES.IconBooksCategory,
    cId: 'category13',
    sub: [
      {sId: '13-01', title: "Audiobooks"},
      {sId: '13-02', title: "Calendars, Notebooks, and Gifts"},
      {sId: '13-03', title: "Children's"},
      {sId: '13-04', title: "Comics"},
      {sId: '13-05', title: "Fiction and Poetry"},
      {sId: '13-06', title: "Non-Fiction"},
      {sId: '13-07', title: "Text Books"},
      {sId: '13-08', title: "Young Adult"},
      {sId: '13-09', title: "Other"},
    ]
  },
]

export const WORLDFODDS = [
  {
    note: 'Spend $30, Save $5',
    title: 'World Foods',
    item: 'Grocery',
    rating: 4.6,
    location: 2.3,
    time: '55-65 min',
    image: IMAGES.Img1Product
  },
  {
    note: '- 30%',
    title: 'Metro',
    item: 'Grocery',
    rating: 4.6,
    location: 2.3,
    time: '55-65 min',
    image: IMAGES.Img2Product
  },
  {
    title: 'Walmart',
    item: 'Grocery',
    rating: 4.6,
    location: 2.3,
    time: '55-65 min',
    image: IMAGES.Img3Product
  },
  {
    title: 'Rexall',
    item: 'Grocery',
    rating: 4.6,
    location: 2.3,
    time: '55-65 min',
    image: IMAGES.Img4Product
  },
  {
    title: 'Metro2',
    item: 'Grocery',
    rating: 4.6,
    location: 2.3,
    time: '55-65 min',
    image: IMAGES.Img5Product
  },
  {
    title: 'Metro3',
    item: 'Grocery',
    rating: 4.6,
    location: 2.3,
    time: '55-65 min',
    image: IMAGES.Img6Product
  },
  {
    title: 'Walmart',
    item: 'Grocery',
    rating: 4.6,
    location: 2.3,
    time: '55-65 min',
    image: IMAGES.Img7Product
  },
  {
    title: 'Metro2',
    item: 'Grocery',
    rating: 4.6,
    location: 2.3,
    time: '55-65 min',
    image: IMAGES.Img8Product
  },
  {
    title: 'Orange Garage',
    item: 'Grocery',
    rating: 4.6,
    location: 2.3,
    time: '55-65 min',
    image: IMAGES.Img9Product
  },
  {
    title: 'Metro2',
    item: 'Grocery',
    rating: 4.6,
    location: 2.3,
    time: '55-65 min',
    image: IMAGES.Img10Product
  },
  {
    title: 'Metro3',
    item: 'Grocery',
    rating: 4.6,
    location: 2.3,
    time: '55-65 min',
    image: IMAGES.Img9Product
  },
  {
    title: 'Walmart',
    item: 'Grocery',
    rating: 4.6,
    location: 2.3,
    time: '55-65 min',
    image: IMAGES.Img8Product
  },
  {
    title: 'Metro2',
    item: 'Grocery',
    rating: 4.6,
    location: 2.3,
    time: '55-65 min',
    image: IMAGES.Img2Product
  },
  {
    title: 'Orange Garage',
    item: 'Grocery',
    rating: 4.6,
    location: 2.3,
    time: '55-65 min',
    image: IMAGES.Img3Product
  },
]

export const ELECTRONICPRODUCTS = [
  {
    img: IMAGES.ImgJoyStickerProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgReceiverProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCameraProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgScreenProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgJoyStickerProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgReceiverProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCameraProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgScreenProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgJoyStickerProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgReceiverProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgCameraProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgScreenProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgJoyStickerProduct,
    new_price: 2.47,
    title: 'Califlower',
    description: 'Price / Unit',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgReceiverProduct,
    new_price: 0.58,
    title: 'Yellow Bananas',
    description: 'Price / LB, 1Price(40Z)',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgScreenProduct,
    new_price: 3.24,
    title: 'Tomato Roma',
    description: 'Solid in Singles',
    color: 'rgb(240, 250, 243)',
  },
  {
    img: IMAGES.ImgJoyStickerProduct,
    new_price: 3.56,
    title: 'Sweet Potato',
    description: 'In Bulk Price/LB',
    color: 'rgb(240, 250, 243)',
  }
]